name: finse_modelling
channels:
  - conda-forge
dependencies:
  - jupyter
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - shapely
  - matplotlib
  - Pillow
  - netcdf4
  - scikit-image
  - scikit-learn
  - configobj
  - xarray
  - pytest
  - dask
  - bottleneck
  - pyproj
  - cartopy
  - geopandas
  - rasterio
  - rioxarray
  - seaborn
  - pytables
  - salem
  - motionless
  - sphinx
  - sphinx-book-theme>=0.3.3
  - ipython
  - ipykernel
  - numpydoc
  - seaborn
  - scikit-learn
  - sphinx-intl
  - sphinx-reredirects
  - pip
  - pip:
    - joblib
    - progressbar2
    - sphinx-togglebutton
    - git+https://github.com/OGGM/pytest-mpl
    - oggm==1.6.0
